### ISSUE TITLE
Updating records appears as unreliable

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#230]
This gave us trouble on the last instance, without a clear resolution. Ticket on that here: https://github.com/culibraries/folio-ansible/issues/26.

I will investigate the logs for errors. One theory is that the s3 storage isn't configured.

**Comment by steveellis** [comment]
@jwfuller I'm trying to replicate and can't seem to figure out how to start an actual data import job. Would be great if you could put in some steps to replicate here.

In mod-source-record-manager (which apparently is in the chain) there are a lot of errors like this. Otherwise I checked mod-copycat and mod-data-import and mod-data-import-converter-storage and don't see any errors.

```
java.net.URISyntaxException: Illegal character in query at index 113: /metadata-provider/jobExecutions?query=(status%20any%20%22COMMITTED%20ERROR%22)%20%20%20AND%20(jobProfileInfo=%22\%E2%80%9Cid\%E2%80%9C==%22%20NOT%20jobProfileInfo=%22\%E2%80%9Cid\%E2%80%9C==%22d0ebb7b0-2f0f-11eb-adc1-0242ac120002%22)%20%20%20AND%20(jobProfileInfo=%22\%E2%80%9Cid\%E2%80%9C==%22%20NOT%20jobProfileInfo=%22\%E2%80%9Cid\%E2%80%9C==%2291f9b8d6-d80e-4727-9783-73fb53e3c786%22)%20%20%20sortBy%20completedDate/sort.descending&limit=25
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3172)
        at java.base/java.net.URI$Parser.parse(URI.java:3125)
        at java.base/java.net.URI.<init>(URI.java:600)
        at io.vertx.core.http.impl.HttpUtils.absoluteURI(HttpUtils.java:482)
        at io.vertx.core.http.impl.Http1xServerRequest.absoluteURI(Http1xServerRequest.java:347)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:53)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
        at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
        at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:194)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:151)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jwfuller** [comment]
1. Go to [Inventory](https://folio.colorado.edu/inventory?filters=&sort=title)
2. From the "Action" menu in the upper right, choose `Import`
3. Enter an OCLC identifier like `1188975991` (can search for records using [WorldCat](https://www.worldcat.org)
4. See the notice that the import is started
5. Visit the [Data import page](https://folio.colorado.edu/data-import) and see that the import task is in progress but does not complete

**Comment by steveellis** [comment]
Ok I can see in mod-copycat that `RecordImporter` attempts 20 times to do the import and then fails with a WARN (didn't show up when I grepped for errors before:

```
21:47:02 [] [] [] [] WARN  RecordImporter       Polling failed and ignored: Did not get any instances after 20 retries
io.vertx.core.impl.NoStackTraceThrowable: Did not get any instances after 20 retries
21:47:02 [] [] [] [] INFO  CopycatImpl          Got no instance identifiers
21:47:02 [] [] [] [] INFO  LogUtil              10.0.130.51:39848 POST /copycat/imports null HTTP_1_1 200 97 6702 tid=cubl OK 
21:47:02 [] [] [] [] INFO  RestRouting          invoking getCopycatProfiles
2
```

Which is the same message that I was seeing in the other ticket. I say I need to investigate the source more to try to figure out what is going on, but I must not have done that since it got resolved by magic. So I'll have to dig around again in the `RecordImporter`.

**Comment by steveellis** [comment]
**It's not mod-copycat**

Looking at the source of mod-copycat just starts an import job which is run in mod-source-record-storage-manager (the `change-manager` route), which is failing with the URI parsing error above. mod-copycat only polls on the result and gives up when it doesn't find the imported record in mod-source-record-storage.

But why is mod-source-record-storage-manager failing with that URI? Just eyeballing the URI and the position 113 it it is complaining about things seem fine. There's no obvious "hey that's an illegal character" thing happening. It's failing when it is constructing the URI object. In any case think the cause is in mod-source-rec-man not mod-copycat.

**Comment by steveellis** [comment]
**The error is likely in mod-source-record-storage**

In the current instance, where it is working, there is no need to go to the data import ui to check on the status of the job. It all completes in the copycat ui.

When the import doesn't work (new Iris instance) the message ui message is: `Record <number> has been queued for import, but is not yet available`.

When it works (on the old instance) the message in the UI is: `Created record <number>`

These strings are available [here](https://github.com/folio-org/ui-inventory/blob/d4a1abe2987446ae6d297c887c5d236691923aa1/translations/ui-inventory/en.json).
```
  "copycat.callout.no-id.created": "Record {xid} has been queued for import, but is not yet available",
  "copycat.callout.no-id.updated": "Record {xid} has been queued for update, but the process is not yet complete",
  "copycat.callout.created": "Created record {xid}",
  "copycat.callout.simpleError": "Something went wrong: {err}",
```
The reason the UI doesn't show the right message is that there is no `internalIdentifier` returned in the response from mod-copycat. This can be seen in the JS source [here](https://github.com/folio-org/ui-inventory/blob/master/src/components/ImportRecord/ImportRecord.js).

In any case it all flows through mod-copycat. Tracing the request in mod-copycat:

CopyCatImpl.postCopycatImports calls
1. RecordImporter.begin which calls RecordImporter.putJobProfile which starts the job at the change-manager endpoint
2. RecordImporter.post which calls "/change-manager/jobExecutions/" + jobId + "/records to start the job.
	1.  ChangeManagerImpl.postChangeManagerJobExecutionsRecordsById
	2. ChunkProcessingService.processChunk
	3. ChangeEngineServiceImpl.getParsedRecordsFromInitialRecords
	4. EventDrivenChunkProcessingServiceImpl.ProcessRawRecordsChunk
3. RecordImporter.end which polls "/source-storage/source-records?snapshotId=" + jobId 20 times

But the end result of all of this is that the /change-manager request to mod-source-record-storage manager sends a message to kafka:
```
8:37:35.354 [vert.x-eventloop-thread-1] INFO  EventHandlingUtil    [1123190877eqId] Event with type: DI_RAW_RECORDS_CHUNK_PARSED and correlationId: null was sent to kafka
18:37:35.985 [vert.x-worker-thread-13] INFO  EventHandlingUtil    [1123191508eqId] Event with type: DI_SRS_MARC_BIB_RECORD_CREATED and correlationId: b7d64692-d41d-46e1-9b76-6f18e3cbbc29 was sent to kafka
```
mod-source-record-storage consumes this message after the source record manager sends it to (see above):
```
18:37:36.000 [vert.x-worker-thread-14] WARN  EventProcessorImpl   [1123177352eqId] No suitable handler found for DI_SRS_MARC_BIB_RECORD_CREATED event type and current profile ACTION_PROFILE
```
*I believe this is the source of the problem.* SRS gets the event, but can't process it because it can't find the handler for the action profile.

Very similar and maybe identical to this: https://issues.folio.org/browse/MODINV-487. 

Although I don't see the corresponding ERROR in mod-inventory that they report. This is only fixed in the Juniper Hotfix #2.

@jwfuller I believe the workaround the mention in the ticket above is:
> Current workaround Use a different action profile (Update MARC Bib) with a field mapping profile of MARC Bib/Update, with no edits. THAT finally worked

This _sounds like what may have fixed it for us previously_ (I believe we may have switch some stuff around with these profiles, or reloaded them). I can't recall. But after we did _something_ it started working. What did we do? Does "using a different action profile" mean anything to you?

**Comment by jwfuller** [comment]
@steveellis Action profile does mean something to me, I will manually recreate the entire import profile and try that out

**Comment by jwfuller** [comment]
@steveellis I followed these steps and ran a new import. I don't think it is working yet. I am going to try duplicating the Update profile and then building the Create Profile from scratch.

1. In `Settings >> Data Import`, I used the `Duplicate` function to recreate the Job, Action, and Field Profiles associated with the `Inventory Single Record - Default Create Instance` Job Profile. 
2. In `Settings >> Inventory >> Integrations (z39.50 target profiles)` edit the ` OCLC WorldCat` profile
3. Update the `Job profile ID for create` value

**Comment by steveellis** [comment]
Seems to have been fixed after restarting the deployments for mod-inventory and mod-inventory-storage. I believe I restarted mod-source-record-storage and mod-source-record-storage-manager in my work above, but not mod-inventory.

**Comment by steveellis** [comment]
@jwfuller Import is working reliably in the scratch env. I said on teams it wasn't but that appears to be wrong. Getting a green toast for 3 imports. Each one with a different oclc number. This is what the logs look like in mod-inventory in the case of this working properly in scratch:
```
22:00:38 [] [] [] [] INFO  Metadata             [Producer clientId=producer-12] Cluster ID: vpY20X5_TjaujQG1OhBOpw
22:00:38 [] [] [] [] INFO  TransactionManager   [Producer clientId=producer-12] ProducerId set to 3007 with epoch 0
22:00:38 [] [] [] [] INFO  KafkaEventPublisher  Event with type: DI_INVENTORY_INSTANCE_CREATED_READY_FOR_POST_PROCESSING and correlationId: 6a5dc37a-ab1a-48a0-810f-7788907b8a0b was sent to the topic cu.Default.cubl.DI_INVENTORY_INSTANCE_CREATED_READY_FOR_POST_PROCESSING
22:00:38 [] [] [] [] INFO  KafkaConsumerWrapper Consumer - id: 4 subscriptionPattern: SubscriptionDefinition(eventType=DI_SRS_MARC_BIB_RECORD_CREATED, subscriptionPattern=cu\.Default\.\w{1,}\.DI_SRS_MARC_BIB_RECORD_CREATED) Committing offset: 3
22:00:38 [] [] [] [] INFO  KafkaProducer        [Producer clientId=producer-12] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
22:00:39 [] [] [] [] INFO  eHridSetKafkaHandler Event payload has been received with event type: DI_SRS_MARC_BIB_INSTANCE_HRID_SET and correlationId: 6a5dc37a-ab1a-48a0-810f-7788907b8a0b
22:00:39 [] [] [] [] INFO  KafkaConsumerWrapper Consumer - id: 1 subscriptionPattern: SubscriptionDefinition(eventType=DI_SRS_MARC_BIB_INSTANCE_HRID_SET, subscriptionPattern=cu\.Default\.\w{1,}\.DI_SRS_MARC_BIB_INSTANCE_HRID_SET) Committing offset: 3
```
When it doesn't work in prod the logs (mod-inventory) look like this:
```
16:06:44 [] [] [] [] ERROR InstanceEventHandler Error posting Instance cause { "message": "cannot execute INSERT in a read-only transaction", "severity": "ERROR", "code": "25006", "file": "utility.c", "line": "246", "routine": "PreventCommandIfReadOnly" }, status code 500
16:06:44 [] [] [] [] ERROR InstanceEventHandler Error creating inventory Instance
io.vertx.core.impl.NoStackTraceThrowable: { "message": "cannot execute INSERT in a read-only transaction", "severity": "ERROR", "code": "25006", "file": "utility.c", "line": "246", "routine": "PreventCommandIfReadOnly" }
16:06:44 [] [] [] [] INFO  KafkaEventPublisher  Event with type: DI_ERROR and correlationId: 58dfe8e9-8c85-4a04-a822-245326747ba5 was sent to the topic cu.Default.cubl.DI_ERROR
16:06:44 [] [] [] [] ERROR KafkaConsumerWrapper Error while processing a record - id: 4 subscriptionPattern: SubscriptionDefinition(eventType=DI_SRS_MARC_BIB_RECORD_CREATED, subscriptionPattern=cu\.Default\.\w{1,}\.DI_SRS_MARC_BIB_RECORD_CREATED)
```
I'm reading that `cannot execute INSERT in a read-only transaction` [could be](https://stackoverflow.com/a/54192844) the result of running out of storage space. Followed instructions [here](https://aws.amazon.com/premiumsupport/knowledge-center/view-storage-aurora-cluster/) for how to view that usage, but the metric `AuroraVolumeBytesLeftTotal` or other combinations of same do not appear to exist in CloudWatch. I can see other metrics like `AuroraVolumeBytesUsed` (it's around 4.5 GB). Could it be that [aurora has autoscaling by default](https://stackoverflow.com/questions/34065157/does-aws-support-autoscaling-for-rds-instance) and that that was a feature which is poorly documented or added at a later date and the docs didn't catch up? That would explain why the metric wasn't available. In any case I don't believe we selected any storage size so I'm skeptical that's the cause.

**Comment by steveellis** [comment]
There are three things that are different between these two envs:
* Kafka has restarted 4 times in scratch, twice in prod. These restarts need to be investigated through the pod's k8s logs.
* Scratch has no scaling. There's one pod for each module.
* The scratch db cluster has one db instance due to the way I created it. Prod has 2.

The backing db for each env is effectively the same, scratch's db having been created from snapshot of prod last week.

**Comment by steveellis** [comment]
I think I have this sorted.

**FOLIO does not currently (Iris) have reliable data writes when you have 2 RDS instances: one which is a reader and one which is a writer.**

If you have more than one instance, RDS  will make the first instance a read-only instance. The second instance will be both a reader and a writer (appearing as a "Writer") in the AWS RDS console. When there are two instances, one being read-only, either FOLIO or RDS (it is currently unknown where the root cause is) the correct endpoint (reader or writer) isn't called. So what will happen is a write will hit the reader and cause an error, not allowing the write to succeed since it is read only.

I think the pattern we've been seeing supports this hypothesis. Sometimes it works, sometimes it doesn't. It appears random.

After removing the writer instance I have been able to import ~10 records without a problem.

I don't think this due to the new `ClusterEndpoint` that was added this week since the problem existed before it. I'm 100% sure that the Writer instance was selected prior to that for the db host.

Theory: FOLIO is sending DB operations to RDS that RDS doesn't know where to route (the reader or the writer).

It is also possible that this was the cause of many of our woes on the old sandbox because I believe its db was configured in the same way.

**Comment by steveellis** [comment]
Also figured out `Illegal character in query at index`. This is noise that occurs in the log of mod-source-record-manager if any user happens to have that app open in the UI. There's a timer that polls the module, and each time it does, the exception is thrown and hits the logs. It is a known issue that should be fixed in Kiwi.
